### ISSUE TITLE
Scan lightning invoice on Bitrefill won't work

### ISSUE THREAD

**Issue by CruiseMan** [BlueWallet/BlueWallet#2640] opened 2021-02-17 21:03 UTC
When scanning QR code nothing happens, but adding actual invoice works.
Invoice: `lnbc383u1pszmq6wpp5h98hcz749ufdgvkjlxcnuflv76tjhpy6q8282x0n7t85whep6nfqdz2gf5hgun9ve5kcmpqxc6rjcn9xymnjtfjvguxgtf58pjxztfexcexvtf4xgmxzde3vvcnvc3hvccqzxgxqrp9ssp5050y4qf95k2nyszjar86322ad98fn5yhjdedlqhrha5cyeftt2xs9qyyssqx0khw6fysh7ez2yjgzeug98t7pym945w9v0deh9f5j4rl322fm9rsvv2pjjnnlcjewfz97nnpj2w9tkv68rsl5vlmuczq6hxp20mmccq59a27m`
<img width="734" alt="Screen Shot 2021-02-17 at 1 01 38 PM" src="https://user-images.githubusercontent.com/15807643/108267609-46769200-7120-11eb-928a-fefd1734a5be.png">

**Comment by ncoelho** [comment] 2021-02-17 21:05
Version of BlueWallet? 

I tested and it worked for me.

**Comment by CruiseMan** [comment] 2021-02-17 21:06
6.0.5 build 1612982073

**Comment by CruiseMan** [comment] 2021-02-17 21:07
And also my balance is still not updated after I made a payment even after couple screen pull downs.

**Comment by ncoelho** [comment] 2021-02-17 21:10
Weird, can't replicate that issue. 

https://user-images.githubusercontent.com/1238429/108268462-d6dac400-716c-11eb-97ee-8f6553cefa2e.mov

**Comment by CruiseMan** [comment] 2021-02-17 21:11
Here is a video, scanning another QR https://www.dropbox.com/s/lxthbngkxbyxab0/IMG_5339.MOV?dl=0

**Comment by CruiseMan** [comment] 2021-02-17 21:12
<img width="868" alt="Screen Shot 2021-02-17 at 1 12 39 PM" src="https://user-images.githubusercontent.com/15807643/108268739-d0732a80-7121-11eb-8e4e-44fda40f0562.png">

**Comment by ncoelho** [comment] 2021-02-17 21:14
ah ok that's a real image, the app doesn't recognize that "QR code", which is not a QR code, it is something else. Let me ask bitrefill guys

**Comment by CruiseMan** [comment] 2021-02-17 21:16
> ah ok that's a real image, the app doesn't recognize that "QR code", which is not a QR code, it is something else. Let me ask bitrefill guys

As yo usan see it doesn't scan QR but I go back and click scan again it pull down invoice with sats amount, expect this result on first scan. SO it scans, but not when it expected.

**Comment by juscamarena** [comment] 2021-02-17 21:30
Hello, dev at bitrefill here. Are you running any special extensions?

If you're open to as well can you tell us what browser you are using? Feel free to contact us support@bitrefill.com so we can fix this. We're not able to reproduce on our end.

**Comment by CruiseMan** [comment] 2021-02-17 21:31
> Hello, dev at bitrefill here. Are you running any special extensions?
> 
> If you're open to as well can you tell us what browser you are using? Feel free to contact us [support@bitrefill.com](mailto:support@bitrefill.com) so we can fix this. We're not able to reproduce on our end.

Using Tor

**Comment by CruiseMan** [comment] 2021-02-17 21:45
> Hello, dev at bitrefill here. Are you running any special extensions?
> 
> If you're open to as well can you tell us what browser you are using? Feel free to contact us [support@bitrefill.com](mailto:support@bitrefill.com) so we can fix this. We're not able to reproduce on our end.

@juscamarena the same happens when scanning LTC QR code from Trust Wallet. I think you using some "funny" qr generation standard that not compatible with major wallets. And when you start supporting `Bech32` address on LTC starting from `ltc1....` its 2021, common. Love your product, but need move forward.

**Comment by Overtorment** [comment] 2021-02-18 12:14
the problem is not on bluewallet's side, QR code is just not valid. 
closing.

**Closed by Overtorment** 2021-02-18 12:14 UTC
