### ISSUE TITLE
Generate fingerprint for watch only wallet

### ISSUE THREAD

**Issue by Mikael-R** [BlueWallet/BlueWallet#6369] opened 2024-04-05 01:11 UTC
Generate fingerprint for watch only wallet

**Comment by Overtorment** [comment] 2024-04-09 15:22
you probably mean 'edit fingerprint' ? because FP is derived from the seed to uniquely identify the seed.

**Comment by AdamuAbba** [comment] 2024-04-11 12:14
hey @Overtorment please is this issue somehow a duplicate of #1261 or an extension of it and Is it also fine if I pick this up?   I'd really appreciate any pointers you can give to me on implementing this. thank you

**Comment by Overtorment** [comment] 2024-04-12 10:14
ah yes, its duplicate of https://github.com/BlueWallet/BlueWallet/issues/1261

@AdamuAbba if you want to implement this then go ahead. basically for HD watch-only wallets instead of displaying text fingerprint you need to display it as an input dialog, and save it (theres a Save button on top right already) if its a valid hex (validate that its 4 bytes)

**Closed by Overtorment** 2024-04-12 10:14 UTC
Labels: help wanted, good first issue 🥇
