### ISSUE TITLE
Crash on language change

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#98] opened 2018-10-07 15:52 UTC
From expo

```
[sentry-expo] Automatically skipping Sentry initialization in development. Note you can set Sentry.enableInExpoDevelopment=true before calling Sentry.config(...).install()
INFO
17:49
loaded from disk
INFO
17:49
got event WALLETS_COUNT_CHANGED ...
INFO
17:49
got event TRANSACTIONS_COUNT_CHANGED ...
INFO
17:49
time to refresh wallet #0
INFO
17:49
Running application "main" with appParams: {"rootTag":1,"initialProps":{"exp":{"manifest":{"description":"Bitcoin wallet app. Alpha version (iOS only)","developer":{"projectRoot":"/Users/nunocoelho/Documents/GitHub/BlueWallet","tool":"expo-cli"},"privacy":"public","assetBundlePatterns":["**/*"],"loadedFromCache":false,"logUrl":"http://192.168.1.35:19000/logs","hooks":{"postPublish":[{"config":{"organization":"bluewallet","project":"bluewallet","authToken":"sentry_api_key"},"file":"sentry-expo/upload-sourcemaps"}]},"orientation":"portrait","xde":true,"id":"@ncoelho/bluewallet","hostUri":"192.168.1.35:19000","iconUrl":"http://192.168.1.35:19001/assets/img/icon.png","mainModuleName":"./node_modules/react-native-scripts/build/bin/crna-entry","sdkVersion":"30.0.0","primaryColor":"#00aced","android":{"package":"io.bluewallet.bluewallet"},"githubUrl":"https://github.com/BlueWallet/BlueWallet","isVerified":true,"packagerOpts":{"lanType":"ip","dev":true,"minify":false,"urlRandomness":"y4-pti","hostType":"lan"},"notification":{"color":"#000000","icon":"https://s3.amazonaws.com/exp-us-standard/placeholder-push-icon.png","iconUrl":"https://s3.amazonaws.com/exp-us-standard/placeholder-push-icon.png"},"ios":{"buildNumber":"93","infoPlist":{"NSLocationWhenInUseUsageDescription":"Discover local stores nearby that accept Bitcoin","ITSAppUsesNonExemptEncryption":false,"NSCameraUsageDescription":"Allow BlueWallet to scan QR codes"},"supportsTablet":true,"bundleIdentifier":"io.bluewallet.bluewallet"},"updates":{"enabled":false},"bundleUrl":"http://192.168.1.35:19001/./node_modules/react-native-scripts/build/bin/crna-entry.bundle?platform=ios&dev=true&minify=false&hot=false&assetPlugin=%2FUsers%2Fnunocoelho%2FDocuments%2FGitHub%2FBlueWallet%2Fnode_modules%2Fexpo%2Ftools%2FhashAssetFiles","version":"2.6.1","platforms":["ios"],"env":{},"debuggerHost":"192.168.1.35:19001","icon":"img/icon.png","slug":"bluewallet","name":"Blue Wallet","splash":{"image":"./img/splash/splash.png","backgroundColor":"#FFFFFF","imageUrl":"http://192.168.1.35:19001/assets/./img/splash/splash.png"}},"initialUri":"exp://192.168.1.35:19000","appOwnership":"expo","shell":0}}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
INFO
17:49
someone subscribed to WALLETS_COUNT_CHANGED
INFO
17:49
someone subscribed to TRANSACTIONS_COUNT_CHANGED
INFO
17:49
got event WALLETS_COUNT_CHANGED ...
INFO
17:49
dispatching event WALLETS_COUNT_CHANGED
INFO
17:49
got event TRANSACTIONS_COUNT_CHANGED ...
INFO
17:49
dispatching event TRANSACTIONS_COUNT_CHANGED
INFO
17:49
tx took 3.125 sec
INFO
17:49
click 0
INFO
17:49
someone subscribed to WALLETS_COUNT_CHANGED
INFO
17:49
someone subscribed to TRANSACTIONS_COUNT_CHANGED
INFO
17:49
refreshFunction()
INFO
17:49
snapped to card # 1
INFO
17:49
click 1
INFO
17:49
someone subscribed to WALLETS_COUNT_CHANGED
INFO
17:49
someone subscribed to TRANSACTIONS_COUNT_CHANGED
INFO
17:49
refreshFunction()
INFO
17:49
setLanguage pt_pt
```

**Comment by Overtorment** [comment] 2018-10-07 23:06
could not reproduce not in master not in development branches

**Comment by Overtorment** [comment] 2018-10-07 23:08
closed in favor of https://github.com/BlueWallet/BlueWallet/pull/96

**Closed by Overtorment** 2018-10-07 23:08 UTC
Labels: UI, bug
