### ISSUE TITLE
'a few seconds ago' transaction wording ....when it wasn't

### ISSUE THREAD

**Issue by shaggy35** [BlueWallet/BlueWallet#2048] opened 2020-11-02 16:58 UTC
Transaction is always named 'a few seconds ago' when it can be days ago depending on fees/confirmation time. Suggest amend wording to grab time when first broadcast and then show confirmation value if 0

**Comment by limpbrains** [comment] 2020-11-03 05:04
Thanks, but it is duplicate of #1699

**Closed by limpbrains** 2020-11-03 05:04 UTC
