### ISSUE TITLE
Reproducible Builds? 

### ISSUE THREAD

**Issue by xrviv** [BlueWallet/BlueWallet#6980] opened 2024-08-26 02:39 UTC
## Proposing a feature?

Greetings BlueWallet team, Danny here from walletscrutiny.com. 

We've been conducting the verification of the reproducibility of bluewallet since version 4.9.1. Our latest review is for 7.0.1 and we are sad that reproducibility is not in the priority of blue wallet. 

We kindly implore you to consider this. 

With thanks, 

Danny

**Comment by Overtorment** [comment] 2024-09-17 06:01
duplicate of https://github.com/BlueWallet/BlueWallet/issues/758 but noted.

**Closed by Overtorment** 2024-09-17 06:01 UTC
