### ISSUE TITLE
Issues with watch only wallet with large number of transactions

### ISSUE THREAD

**Issue by thestick613** [BlueWallet/BlueWallet#1337] opened 2020-07-08 06:32 UTC
- The app stopped responding, and was generally very slow, but updating to 5.5.0 seemed to fix this.
- The balance was incorrect (only 25% of the correct amount), and a lot of transactions missing, so i deleted the wallet and reimported it.
- Successful reimport, relatively fast, but the balance is still incorrect (only 50% of the correct amount). When i tapped on the wallet, it showed no transactions (Your transactions will appear here), so i dragged the panel down to refresh the tx. It refreshed for a while, then it raised an error.

**Comment by curculluca** [comment] 2020-07-12 05:34
Yaeh! And my coins are frozen since couple of months. But the issue is by me more with bitcoin core. I was waiting so long to receive them, and I thought there’s a better option with BlueWallet. Anyways I’m still waiting because of watch only wallet😬

**Comment by Overtorment** [comment] 2020-07-20 16:43
@thestick613  whats the error message? how many transactions you have? by my calculations, wallets with >2000 txs _can_ throw an error because internal storage is full

**Comment by thestick613** [comment] 2020-07-20 17:12
The error disappeared very fast, but i think it was something like "socket connection error". There are 1400-1500 transactions.

**Comment by Overtorment** [comment] 2020-07-24 15:15
socket error should not affect the app.
if you have several wallets and total transactions count exceeds 2000 then it might throw storage errors.
here's a ticket to track it: https://github.com/BlueWallet/BlueWallet/issues/1319
Ill close this ticket.

**Closed by Overtorment** 2020-07-24 15:15 UTC
