### ISSUE TITLE
idiotic coin selection

### ISSUE THREAD

**Issue by Transisto** [BlueWallet/BlueWallet#3113] opened 2021-05-06 20:03 UTC
Wallet goes out of it's way again to use extra UTXO in my wallet, including in a large unconfirmed parent that I only expected to clear this week-end.

Seriously WTF, 

The wallet won't let us send unconfirmed UTXO unless explicitly selected but loves to spend unconfirmed change when it's not even necessary.

Blue devs can DM me on telegram to get the exact transaction details.

**Comment by Transisto** [comment] 2021-05-06 21:01
Example amounts

0.1btc
1btc  (unconfirmed change of large low fee tx)
2btc
3btc

amount to be sent 2.5
1 2 and 3 used while only 3btc could have been enough.

0.1 wasn't selected, no idea why it was ignored.

**Comment by limpbrains** [comment] 2021-05-09 08:54
Using unconfirmed UTXO was introduced at #887

**Comment by Transisto** [comment] 2021-05-09 13:18
That's only a small part of the problem, using unconfirmed when you
absolutely don't have to is the main problem.

It's destroying privacy and cost more in fees. For so far zero good
reasons.

**Comment by Overtorment** [comment] 2021-05-10 15:20
coin select was fixed in another ticket.
as for unconfirmed utxo, we have a ticket to add the option "use only confirmed utxo" in send transaction details

**Comment by Transisto** [comment] 2021-05-19 20:00
> coin select was fixed in another ticket.
> as for unconfirmed utxo, we have a ticket to add the option "use only confirmed utxo" in send transaction details

What other ticket? I've just sent BTC with latest version and same problem, paying x2 the fees because wallet want to touch every  UTXO

**Comment by Overtorment** [comment] 2021-05-20 09:18
> > coin select was fixed in another ticket.
> > as for unconfirmed utxo, we have a ticket to add the option "use only confirmed utxo" in send transaction details
> 
> What other ticket? I've just sent BTC with latest version and same problem, paying x2 the fees because wallet want to touch every UTXO

it was fixed & merged, but not released. will be included in `v6.1.3` which is due today or tomorrow

**Comment by limpbrains** [comment] 2021-07-06 13:29
Should be already fixed

**Closed by limpbrains** 2021-07-06 13:29 UTC
