### ISSUE TITLE
Enclosed in the creation of multisig wallet [Proposed BUG]

### ISSUE THREAD

**Issue by Alarez777** [BlueWallet/BlueWallet#2969] opened 2021-04-16 09:51 UTC
The problem arises by wanting to create a multisig wallet that is not the default (2 of 3). Because when you go into the option to modify it, there's no longer a way out and to go out, it only remains to close the app.
This problem only happens to me on an iPhone SE 2016 I imagine it happens because the screen size is very small. So it should also affect other devices like the iPhone 5 and 5s.
![IMG_0007](https://user-images.githubusercontent.com/60858814/115006396-70250e80-9e6e-11eb-81fb-6138e495932c.PNG)

**Comment by limpbrains** [comment] 2021-04-16 16:51
related to #2584

**Comment by Overtorment** [comment] 2021-04-17 11:07
duplicate of  #2584 
cc @marcosrdz

**Closed by Overtorment** 2021-04-17 11:07 UTC
