### ISSUE TITLE
Status bar is broken at new wallet dialog

### ISSUE THREAD

**Issue by dimaatmelodromru** [BlueWallet/BlueWallet#944] opened 2020-04-04 08:27 UTC
iPhone SE
![3CCB5460-53DF-4F23-9A4A-B6D501AFB0CA](https://user-images.githubusercontent.com/4951450/78422344-42a46300-7667-11ea-9826-5d95707b9333.png)

**Comment by ncoelho** [comment] 2020-04-04 16:32
what is the OS version?

**Comment by dimaatmelodromru** [comment] 2020-04-05 06:43
13.3.1

**Comment by ncoelho** [comment] 2020-05-11 08:47
Closing can't reproduce

**Closed by ncoelho** 2020-05-11 08:47 UTC
Labels: UI, bug
