### ISSUE TITLE
Import key fails and returns to camera when creating Multisig Vault

### ISSUE THREAD

**Issue by niko-underwood** [BlueWallet/BlueWallet#6202] opened 2024-02-29 18:18 UTC
I am using BW 6.5.5. I'm also trying to create a 2 of 3 Multisig vault. I'm trying to import the key vs scanning with a QR code (I've tried both). When I select import file, select the key generated from the other wallet, BlueWallet just brings me back to the camera looking to scan a QR code. 

I've replicated the on the MacOS desktop running BW 6.5.5 as well as other 3 other iOS devices running 17.3.1

Thanks

_Originally posted by @niko-underwood in https://github.com/BlueWallet/BlueWallet/issues/6105#issuecomment-1971694696_

**Comment by Overtorment** [comment] 2024-03-01 08:59
is that a duplicate of https://github.com/BlueWallet/BlueWallet/issues/6105 ?
closing if so

**Closed by Overtorment** 2024-03-01 08:59 UTC
Labels: duplicate

**Comment by niko-underwood** [comment] 2024-03-01 11:30
This happens while using the file import option to import a key in a  new vault, in addition to using the camera to scan a QR Code. If this was resolved as part of that, it can be closed. Thanks!

**Comment by niko-underwood** [comment] 2024-03-01 11:59
I just downloaded BlueWallet v 6.5.6 and tested both the QR scan as well as the file import option. The camera still scans at 99/100 and the import option just returns back to the camera after the file is selected.

**Comment by Overtorment** [comment] 2024-03-01 17:26
fix not released yet

**Comment by Overtorment** [comment] 2024-03-01 22:04
should be out in .7
