### ISSUE TITLE
"This wallet doesn't have any coins" after legacy p2pkh import

### ISSUE THREAD

**Issue by cbeams** [BlueWallet/BlueWallet#2505] opened 2021-01-17 14:25 UTC
## Steps to reproduce

1. I swept a private key from a Coldcard into freshly-installed BlueWallet on Android
2. The wallet showed up as expected with the correct balance, labeled "Legacy P2PKH"
3. I attempted to spend from the legacy wallet to an empty native SegWit wallet in the same BlueWallet app
4. I was presented with an error that I didn't have sufficient funds to so
5. Attempting to troubleshoot via coin control, I saw a message reading "This wallet doesn't have any coins"

## Workaround

In the end, I abandoned the attempt and imported the same private key into Electrum and spent the funds from there without issue.

----

Any ideas what might have happened here? Given how it went, I think anyone attempting the same workflow would have the problem.

**Comment by Overtorment** [comment] 2021-01-18 14:52
could not reproduce. maybe connectivity issue..?
did coldcard, electrum & bluewallet agree on receiving address?
were coins confirmed on that wallet, or all unconfirmed?

**Comment by Overtorment** [comment] 2021-01-18 14:57
wild guess, was Electrum Personal Server used?

**Comment by Overtorment** [comment] 2021-01-26 12:13
hopefully fixed by https://github.com/BlueWallet/BlueWallet/pull/2530

**Closed by Overtorment** 2021-01-26 12:13 UTC
