### ISSUE TITLE
Bug: BlueWallet can't find all transactions on imported multisig wallet

### ISSUE THREAD

**Issue by jordan-bravo** [BlueWallet/BlueWallet#5699] opened 2023-09-24 19:44 UTC
## Steps to reproduce

1. Using a different wallet software, e.g. Sparrow wallet, I created a 2-of-3 multisig wallet that uses hardware signing devices.
2. In Sparrow, I exported the wallet.  I have tried several different export formats to import into BlueWallet but they all lead to the same result.  For example, if select the BlueWallet export option, the following file is exported:
```
# Blue Wallet Vault Multisig setup file (created by Sparrow)
#
Name: ColdStorageMultiSig
Policy: 2 of 3
Derivation: m/48'/0'/0'/2'
Format: P2WSH

<redacted>: xpub6<redacted>
<redacted>: xpub6<redacted>
<redacted>: xpub6<redacted>
```
3. Import into BlueWallet

## Expected result
BlueWallet should show full transaction history and show up to date balance.

## Actual result
BlueWallet shows transactions and balance only as recently as 7 months ago, despite having more recent transactions and different up-to-date balance.

## System info

Device: Google Pixel 6
OS: Android 13 with the [latest release of GrapheneOS](https://grapheneos.org/releases#2023091800)
BlueWallet version: 6.4.8 (build 1690407983)
Unique ID: `40c3a0c5df835a3a`
Self-test: OK. All internal tests have passed successfully.

**Comment by silkroadnomad** [comment] 2024-03-31 16:40
I can confirm that on my wallet and on a wallet of a friend of mine not all transactions seem to be visible without importing anything from somewhere else.

We own the Bluewallet since years but used it mainly for "hodling". 
Maybe there is a way to re-synchronize all transactions? 

Interesting: The amount of transactions in the details screen seems correct but the transactionlist shows less.

**Comment by Overtorment** [comment] 2024-03-31 18:02
I suspect the issue is in gap limit. 
For multisig BW has 10.

Can you explore your wallet in Sparrow and see if there are gaps of unused addresses? If there are at least 10 consecutive ones BW wont "see" the ones after.

I suppose we can bump to 20 (industry standard), but would be nice to confirm first.

**Comment by jordan-bravo** [comment] 2024-04-27 15:56
Yes, I originally created the wallet in Sparrow, and I can see a gap of 17 unused addresses between the used addresses.

**Comment by Overtorment** [comment] 2024-04-28 08:01
Understood. I'll bump the gap limit to 20 for multisig wallets (the industry standard)

**Comment by Overtorment** [comment] 2024-05-01 20:41
fixed in https://github.com/BlueWallet/BlueWallet/pull/6498

should be out with next release. 
you should not need to reimport ms wallets, but in case problem persists - reimport might help

**Closed by Overtorment** 2024-05-01 20:41 UTC
