### ISSUE TITLE
Cannot read properties of undefined 'transformFile'

### ISSUE THREAD

**Issue by RtlCyclone** [BlueWallet/BlueWallet#4140] opened 2021-10-30 10:05 UTC
**Virtual Device:**
Name: Pixel_2_API_29
CPU/ABI: Google Play Intel Atom (x86)
API level 29

i downloaded the latest source but after syncing grandle and running `npx react-native run-android` i get this error:

```
Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at stableHash (C:\Users\Cyclone\Downloads\BlueWallet-master\node_modules\metro-cache\src\stableHash.js:19:8)
    at Object.getCacheKey (C:\Users\Cyclone\Downloads\BlueWallet-master\node_modules\metro-transform-worker\src\index.js:647:7)
    at getTransformCacheKey (C:\Users\Cyclone\Downloads\BlueWallet-master\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js:32:19)
    at new Transformer (C:\Users\Cyclone\Downloads\BlueWallet-master\node_modules\metro\src\DeltaBundler\Transformer.js:180:28)
    at C:\Users\Cyclone\Downloads\BlueWallet-master\node_modules\metro\src\Bundler.js:58:29 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
 BUNDLE  ./index.js

error: TypeError: Cannot read properties of undefined (reading 'transformFile')
    at C:\Users\Cyclone\Downloads\BlueWallet-master\node_modules\metro\src\Bundler.js:95:34
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\Cyclone\Downloads\BlueWallet-master\node_modules\metro\src\Bundler.js:14:24)
    at _next (C:\Users\Cyclone\Downloads\BlueWallet-master\node_modules\metro\src\Bundler.js:36:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Overtorment** [comment] 2021-11-01 17:01
no idea mate. `opensslErrorStack` suggests some network issues..?

ps. i usually run `npm run android`

**Comment by marcosrdz** [comment] 2021-11-03 16:31
Run: nom start -- --reset-cache
at the root folder of the project, and then run the app

**Comment by brel01** [comment] 2022-02-17 12:26
Hello, how did you later handle it? I'm have the same problem

**Comment by kusaljr** [comment] 2022-02-19 10:32
I'm getting same error, any fixes?

**Comment by Overtorment** [comment] 2022-02-19 12:08
i sense the problem is in windows. delete it and install linux

**Comment by izjing** [comment] 2022-03-19 08:18
> 

有效

**Comment by kusaljr** [comment] 2022-03-19 12:08
This can be fixed by upgrading JDK.

**Closed** 2022-03-20 11:39 UTC
Labels: cannot reproduce 🙈
