### ISSUE TITLE
Error importing zpub key: "Failed to import. Please, make sure that the provided data is valid"

### ISSUE THREAD

**Issue by danbadjar** [BlueWallet/BlueWallet#501] opened 2019-05-23 09:56 UTC
Hello,
I'm trying to import a zpub key (Electrum segwit) but I obtain this error:

"Failed to import. Please, make sure that the provided data is valid"

Android
Bluewallet 4.0.1

**Comment by danbadjar** [comment] 2019-05-28 09:47
Upgraded to 4.0.2
Problem persists

**Comment by Overtorment** [comment] 2019-06-08 13:00
should be fixed  in https://github.com/BlueWallet/BlueWallet/pull/514.
will rollout in v4.0.4

**Comment by netxecute** [comment] 2019-08-16 15:46
am on 4.1.0 and still get this error for both zpub generated by cold card wallet 
Bitcoin Core  (segwit P2PKH) m
BIP84 native (native segwit P2PKH) m/84'/0'

also cannot import ypub at all, just spins

I noticed 4.2.0 is out, will try it when I get a chance

**Comment by Overtorment** [comment] 2019-08-17 11:39
Can you share faulty xpub/zpub privately to i@bluewallet.io ?
This needs to be investigated.

**Comment by netxecute** [comment] 2019-10-21 18:30
now on 4.5.2 - still get the error
I'd sent in examples - is there any update?

**Comment by Overtorment** [comment] 2019-10-21 18:43
I thought I fixed. Will test again.

**Comment by Overtorment** [comment] 2019-10-23 21:24
> now on 4.5.2 - still get the error
> I'd sent in examples - is there any update?

Can you email it to me again? I have several in my inbox, and they all work fine when tested (just take 60-70 sec to import)

**Comment by netxecute** [comment] 2019-11-13 17:36
Any update?

**Comment by netxecute** [comment] 2019-11-13 17:45
Just tested with version 4.7.1 build 1572387207
Native segwit zpub imported OK. 
BlueWallet gave me different first address than cold card. What is the derivation path? 

m/84'/0'/0'/0/0    ??

**Comment by netxecute** [comment] 2019-11-13 17:48
Core (m/0'/0'/0) is off too when I import that zpub

**Comment by Overtorment** [comment] 2019-11-14 22:48
Path is default for BIP 84, `m/84'/0'/0'/0/0` 
see https://github.com/BlueWallet/BlueWallet/blob/b34700288123e1a8621e0a3423bff9d496d3070c/class/hd-segwit-bech32-wallet.js#L125

There are tests for that  here https://github.com/BlueWallet/BlueWallet/blob/b34700288123e1a8621e0a3423bff9d496d3070c/tests/integration/hd-segwit-bech32-wallet.test.js#L147

My guess is that you have some addresses used in your hierarchy. BW tries to find first *unused* external address ( that has zero transactions) to preserve privacy.

**Comment by netxecute** [comment] 2019-11-14 23:09
OK I can look into the tests and see if I can run them, but..

If the address is used, ie. received some btc, then wallet should show the balance, no? It shows 0.
Also coldcard gives the first 5 addresses, I know I have only done 1 small transaction and it doesn't match any.

**Comment by Overtorment** [comment] 2019-11-14 23:12
Unless it’s spent.
Something is not right here. Tests pass, you can take zpub from tests and
check for yourself

**Comment by netxecute** [comment] 2019-11-15 16:20
Confirmed tests work.

**Comment by Overtorment** [comment] 2019-11-16 23:42
Yeah so the problem is somewhere else, addresses derive okay

**Comment by seth586** [comment] 2020-02-20 06:32
Same error with BlueWallet 4.9.4, entering the zpub from my coldcard results in "Failed to import. Please, make sure that the provided data is valid."

**Comment by ncoelho** [comment] 2020-05-11 08:44
Can someone confirm that the issue still exists please?

**Closed** 2020-05-11 08:46 UTC
Labels: bitcoin, help wanted

**Comment by cconcannon** [comment] 2021-05-05 20:13
I'm experiencing this issue trying to import a zpub

BlueWallet ver 6.1.1 (build 1620062553)

**Comment by limpbrains** [comment] 2021-05-06 09:52
I created a wallet in electrum, successfully imported it's zpub to BW, and it shows me the correct receiving address.
